---
- name: Generate service env files from encrypted secrets
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml

  tasks:
    - name: Generate account-service .env
      include_tasks: ../trading-backend/cmd/account-service/formation.yml
      tags:
        - account-service

    - name: Generate stock-screener .env
      include_tasks: ../trading-backend/cmd/stock-screener/formation.yml
      tags:
        - stock-screener

    - name: Generate authentication-service .env
      include_tasks: ../trading-backend/cmd/authentication-service/formation.yml
      tags:
        - authentication-service

    - name: Generate frontend .env
      include_tasks: ../trading-frontend/formation.yml
      tags:
        - frontend
