#!/bin/bash
# Manage docker-compose for trading-formation. All external traffic goes through
# Traefik on :80 at <subdomain>.<domain>. When proxy.conf flags a service as 1,
# it is excluded from compose; the host-side `make run-<svc>` writes its
# ephemeral port to .proxy-port-<svc>, and this script generates a Traefik
# dynamic file routing <subdomain>.<domain> -> host.docker.internal:<port>.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

COMPOSE_CMD=(docker compose -f "$SCRIPT_DIR/docker-compose.yml" --project-directory "$SCRIPT_DIR")
PROXY_CONF="proxy.conf"
DYNAMIC_DIR="$SCRIPT_DIR/traefik-dynamic"

SERVICES=(
    "account-service:ACCOUNT_SERVICE:/accounts/v1"
    "stock-screener:STOCK_SCREENER:/stock-screener/v1"
    "authentication-service:AUTH_SERVICE:/auth/v1"
    "bot-service:BOT_SERVICE:/bots/v1"
    "reporting-service:REPORTING_SERVICE:/reports/v1"
    "storage-service:STORAGE_SERVICE:/storage/v1"
    "journal-service:JOURNAL_SERVICE:/journal/v1"
)

# Reads top-level `domain:` from services.yml without needing a YAML parser.
DOMAIN="$(awk '/^domain:/ {print $2; exit}' services.yml)"

path_prefix_for() {
    for entry in "${SERVICES[@]}"; do
        IFS=':' read -r svc _ prefix <<<"$entry"
        if [[ "$svc" == "$1" ]]; then echo "$prefix"; return; fi
    done
}

write_dynamic_route() {
    local svc="$1" port="$2" prefix
    prefix="$(path_prefix_for "$svc")"
    mkdir -p "$DYNAMIC_DIR"
    cat > "$DYNAMIC_DIR/$svc.yml" <<EOF
# Generated by run-services.sh — proxy route for $svc.
http:
  routers:
    $svc:
      rule: "Host(\`$DOMAIN\`) && PathPrefix(\`$prefix\`)"
      service: $svc
      entryPoints: [web]
  services:
    $svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:$port"
EOF
}

remove_dynamic_route() {
    rm -f "$DYNAMIC_DIR/$1.yml"
}

read_proxied_services() {
    proxied=()
    [[ -f "$PROXY_CONF" ]] || return 0
    # shellcheck disable=SC1090
    source "./$PROXY_CONF"
    for entry in "${SERVICES[@]}"; do
        IFS=':' read -r svc var _ <<<"$entry"
        val="${!var:-0}"
        if [[ "$val" == "1" ]]; then
            proxied+=("$svc")
        fi
    done
    return 0
}

require_compose_file() {
    if [[ ! -f docker-compose.yml ]]; then
        echo "docker-compose.yml not found. Run './run-services.sh render' first." >&2
        exit 1
    fi
}

# Polls .proxy-port-<svc> and rewrites the dynamic route when it changes.
# Called in the background after `up` so dev workflow is: terminal A runs this
# script, terminal B runs `make run-<svc>`, Traefik picks up the route.
watch_proxy_ports() {
    local svc port last
    while sleep 2; do
        for svc in "${proxied[@]}"; do
            local f="$SCRIPT_DIR/.proxy-port-$svc"
            if [[ -f "$f" ]]; then
                port="$(<"$f")"
                last="$(cat "$DYNAMIC_DIR/$svc.last" 2>/dev/null || true)"
                if [[ "$port" != "$last" ]]; then
                    write_dynamic_route "$svc" "$port"
                    echo "$port" > "$DYNAMIC_DIR/$svc.last"
                    echo "[proxy] $svc → host.docker.internal:$port"
                fi
            else
                if [[ -f "$DYNAMIC_DIR/$svc.yml" ]]; then
                    remove_dynamic_route "$svc"
                    rm -f "$DYNAMIC_DIR/$svc.last"
                    echo "[proxy] $svc route removed"
                fi
            fi
        done
    done
}

bring_up() {
    local build_flag="${1:-}"
    require_compose_file
    read_proxied_services
    mkdir -p "$DYNAMIC_DIR"

    if [[ ${#proxied[@]} -eq 0 ]]; then
        echo "Starting all services..."
        "${COMPOSE_CMD[@]}" up ${build_flag} -d
        return
    fi

    local all=() dockerized=()
    for entry in "${SERVICES[@]}"; do all+=("${entry%%:*}"); done
    for s in "${all[@]}"; do
        local skip=0
        for p in "${proxied[@]}"; do
            [[ "$s" == "$p" ]] && { skip=1; break; }
        done
        [[ $skip -eq 0 ]] && dockerized+=("$s")
    done

    echo "Dockerized: ${dockerized[*]} frontend traefik"
    echo "Proxied (host): ${proxied[*]}"
    "${COMPOSE_CMD[@]}" up ${build_flag} -d traefik "${dockerized[@]}" frontend

    for svc in "${proxied[@]}"; do
        "${COMPOSE_CMD[@]}" rm -fs "$svc" >/dev/null 2>&1 || true
    done

    echo
    echo "Run each proxied service in its own terminal:"
    for svc in "${proxied[@]}"; do
        echo "  make -C ../trading-backend run-$svc"
    done
    echo
    echo "Then run './run-services.sh watch' in another terminal to keep Traefik"
    echo "routes in sync with each host process's ephemeral port."
}

teardown_proxy_routes() {
    [[ -d "$DYNAMIC_DIR" ]] || return 0
    # Only remove per-service proxy files — never static.yml (the rendered
    # baseline route table). Walk SERVICES so we touch known names only.
    for entry in "${SERVICES[@]}"; do
        IFS=':' read -r svc _ _ <<<"$entry"
        rm -f "$DYNAMIC_DIR/$svc.yml" "$DYNAMIC_DIR/$svc.last" 2>/dev/null || true
    done
}

case "${1:-}" in
    start) bring_up "--build" ;;
    up)    bring_up "" ;;
    watch)
        require_compose_file
        read_proxied_services
        if [[ ${#proxied[@]} -eq 0 ]]; then
            echo "No proxied services in $PROXY_CONF — nothing to watch."
            exit 0
        fi
        echo "Watching ${proxied[*]} (Ctrl-C to stop)"
        watch_proxy_ports
        ;;
    kill)
        echo "Stopping containers and clearing proxy routes..."
        teardown_proxy_routes
        "${COMPOSE_CMD[@]}" down --remove-orphans
        ;;
    delete)
        echo "Purging containers, images, volumes, and proxy routes..."
        teardown_proxy_routes
        "${COMPOSE_CMD[@]}" down --volumes --remove-orphans --rmi local
        docker container prune -f
        docker image prune -f
        docker volume prune -f
        echo "Docker purge completed"
        ;;
    render)
        echo "Generating .env files and Makefile from secrets..."
        sudo ansible-playbook playbook.yml --ask-vault-pass
        ;;
    proxy)
        if [[ ! -f "$PROXY_CONF" ]]; then
            {
                echo "# Set a service to 1 to run it on the host (proxy mode)."
                echo "# 'start'/'up' will exclude flagged services from docker-compose;"
                echo "# 'make run-<svc>' picks a free port and Traefik routes the"
                echo "# service hostname to host.docker.internal on that port."
                echo
                for entry in "${SERVICES[@]}"; do
                    IFS=':' read -r _ var _ <<<"$entry"
                    echo "$var=0"
                done
            } > "$PROXY_CONF"
            echo "Created $PROXY_CONF."
        fi
        "${EDITOR:-vi}" "$PROXY_CONF"
        ;;
    status)
        read_proxied_services
        if [[ ${#proxied[@]} -eq 0 ]]; then
            echo "No proxied services configured."
        else
            for svc in "${proxied[@]}"; do
                f="$SCRIPT_DIR/.proxy-port-$svc"
                if [[ -f "$f" ]]; then
                    echo "running:     $svc on host port $(<"$f")"
                else
                    echo "not running: $svc (no .proxy-port file)"
                fi
            done
        fi
        ;;
    *)
        cat <<EOF
Usage: $0 <command>

  start    docker compose up --build -d   (proxy.conf flagged services excluded)
  up       docker compose up -d           (proxy.conf flagged services excluded)
  watch    Keep Traefik routes in sync with host process ephemeral ports
  kill     Stop containers and clear Traefik proxy routes
  delete   Purge containers, images, volumes
  render   Generate .env files and Makefile via ansible-playbook
  proxy    Seed/edit proxy.conf — flag a service as 1 to run it on the host
  status   Show which proxied services have an active host port file
EOF
        exit 1
        ;;
esac
