---
services:
  account_service:
    scheme: http
    container: { host: account-service, port: 9000 }
    local:     { host: localhost,        port: 9000 }
  stock_screener:
    scheme: http
    container: { host: stock-screener, port: 8080 }
    local:     { host: localhost,       port: 8080 }
  auth_service:
    scheme: http
    container: { host: authentication-service, port: 9100 }
    local:     { host: localhost,                port: 9100 }
  bot_service:
    scheme: http
    container: { host: bot-service, port: 8080 }
    local:     { host: localhost,    port: 8081 }
  reporting_service:
    scheme: http
    container: { host: reporting-service, port: 8082 }
    local:     { host: localhost,          port: 8082 }
  storage_service:
    scheme: http
    container: { host: storage-service, port: 8083 }
    local:     { host: localhost,        port: 8083 }
  journal_service:
    scheme: http
    container: { host: journal-service, port: 8084 }
    local:     { host: localhost,        port: 8084 }
