---
- name: Reset service environment
  set_fact:
    service_environment: {}

- name: Merge resources into service environment
  set_fact:
    service_environment: "{{ service_environment | combine(lookup('vars', item.0.key)[item.1]) }}"
  loop: "{{ resources | dict2items | subelements('value') }}"
  loop_control:
    label: "{{ item.0.key }}.{{ item.1 }}"

- name: Render .env
  template:
    src: "{{ playbook_dir }}/templates/service.env.j2"
    dest: "{{ env_dest }}"
    mode: '0600'
